### ISSUE TITLE
里图文件名乱码时保存图片会直接闪退

### ISSUE THREAD

**Issue by qianrongze** [fEndman/WarFactory#3]
如题，1.6 版本下会出现的问题
我猜可能是文件名编码不支持吧
来自miui程序多次崩溃后的日志摘要：
android.runtime.JavaProxyThrowable: System.UnauthorizedAccessException: Access to the path "/storage/emulated/0/Pictures/战车工厂/�1 (35).jpg" is denied.
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x001b7] in <8ec4f05fd43b4a7b9dd8c9388e639bee>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode) [0x00000] in <8ec4f05fd43b4a7b9dd8c9388e639bee>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode)
  at WarFactory.Droid.PlatformService.ImageSave (System.IO.MemoryStream stream, System.Boolean compatibleMode, System.String fileName) [0x001d4] in <6e9daa9002f04363a2b49c0e5036e90c>:0 
  at WarFactory.ViewPage.LsbTankPage.Button_Clicked_3 (System.Object sender, System.EventArgs e) [0x00180] in <9fc01cd9af1b477a81ecf62686c5decb>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <8ec4f05fd43b4a7b9dd8c9388e639bee>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <945ac9ac2a4d4a1eb9e1be70d23fa635>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <945ac9ac2a4d4a1eb9e1be70d23fa635>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <945ac9ac2a4d4a1eb9e1be70d23fa635>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.58(intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8130)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
示例文件
![Tank_20210723_002059_1](https://user-images.githubusercontent.com/92971076/160240756-5995e6a8-e23c-47b8-b76b-f878bce955aa.png)

**Comment by fEndman** [comment]
报错貌似只是没给文件访问权限的问题。我在我这试了一下，文件名乱码但是能够保存。你看看其他图片是否会出问题，或者到设置里手动打开文件读写权限。这个app不打算继续维护了，如果还是无法解决，这里有个网页html
[index.zip](https://github.com/fEndman/WarFactory/files/8355494/index.zip)

**Comment by qianrongze** [comment]
我已经确定 战车工厂应用已被授予文件访问权限，该软件基于什么版本的安卓开发来着？我记得安卓11大改了文件管理机制，不是谷歌自带的文件管理器 没法访问android/data目录了，系统相册在写入数据的时候 也需要单独授权访问相册目录了，而且很不幸的是 用VIA打开的离线网页端也会出现问题，提示下载失败，以前我有用过小米浏览器打开的网页端没有什么问题，我甚至为了确保不出问题 把下载器设回系统自带试了一遍，还是失败

**Comment by qianrongze** [comment]
那个文件名乱码让我觉得很眼熟，以UTF系列打开的乱码 就是这样的，是不是默认的utf8？

**Comment by qianrongze** [comment]
我大概知道是什么锅了，系统权限管理的读写文件权限没管这个，虽然这个权限对于流氓软件来说很危险 但我想个人开发者应用应该不会搞什么骚操作
![Screenshot_2022-03-26-21-57-13-931_rikka appops](https://user-images.githubusercontent.com/92971076/160242760-fbda9336-a0b1-451e-8797-9ea005dd3e47.jpg)

**Comment by qianrongze** [comment]
坏消息，Appops里授予所有文件读写权限也没用

**Comment by qianrongze** [comment]
小米自带浏览器跑网页端没什么问题，就是下载时文件名和拓展名反过来了，还真是玄学，难道是小米浏览器的89.0.4389.116内核相对vIa调用的97.0.4692.70内核和edge DEV的99.0.4826.0内核支持特性更多吗

**Comment by fEndman** [comment]
安卓各种版本的兼容性真是感人。。我在之前的版本已经处理过高版本安卓权限的问题了，不过这app是使用xamarin开发的，而不是原生安卓sdk，可能并不能很好的处理。如果网页端都会出各种问题，那app里估计会很难处理了

**Comment by qianrongze** [comment]
我看看电脑端跑这个html行不行

**Comment by qianrongze** [comment]
电脑端是99内核的edge

**Comment by qianrongze** [comment]
还真是奇了怪了 89内核的小米自带浏览器就可以下载，其他内核版本高一点的浏览器跑网页端的时候会提示无法下载 用via调用idm+的时候会提示无法连接到这样的主机名，还真是玄学，雨见浏览器干脆直接无法打开本地html文件，换内核都来不及，光速闪退

**Comment by qianrongze** [comment]
![Screenshot 2022_03_26 23_02_15](https://user-images.githubusercontent.com/92971076/160245388-bdf80d12-7b5f-4be6-b308-986767489e6b.png)
PC端的edge没这问题，就是玄学兼容性问题

**Comment by qianrongze** [comment]
文件名没有问题，就是带一个奇怪的括号（大约是罪魁祸首，有文件系统不支持的字符）
